from dataclasses import dataclass
from typing import Optional

from .enums import OrderStatus


@dataclass(frozen=True)
class Proof:
    """
    Semantic predecessor claim attached to a candidate event.

    Important meaning:
    - proof is generated by the aggregate at candidate-event creation time
    - proof is NOT external truth by itself
    - Compass Layer 1 compares this claim against accepted history

    Field ownership:
    - prev_status: aggregate current status before candidate creation
    - prev_version: aggregate current version before candidate creation
    - prev_event_id: aggregate last accepted event id before candidate creation

    This keeps predecessor claims inside the domain transition boundary,
    rather than allowing arbitrary outside injection.
    """
    prev_status: OrderStatus
    prev_version: int
    prev_event_id: Optional[str]